[meta]
name = "Bonk!"
author = "MisfitMaid"
category = "Audio"
version = "1.2.3"
siteid = 314

[script]
dependencies = ["VehicleState"]
optional_dependencies = ["MLHook", "MLFeedRaceData"]
exports = [ "Export.bonk.as" ]
module = "bonk"
